sudo: required
language: ruby
rvm:
  # - 1.9.3
  # - 2.0.0
  # - 2.1
  - 2.2
script:
  - bundle exec rspec
  - bundle exec cucumber
gemfile:
  - Gemfile
before_install:
  - | # cached install of Neo4j locally:
    if [ ! -d neo4j-community-2.3.3/bin ];
    then
      wget dist.neo4j.org/neo4j-community-2.3.3-unix.tar.gz;
      tar -xzf neo4j-community-2.3.3-unix.tar.gz;
      sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-2.3.3/conf/neo4j-server.properties;
    fi
  - docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Travis:1' -p 1433 --name sqlserver -d mcr.microsoft.com/mssql/server:2017-latest-ubuntu
before_script:
  - neo4j-community-2.3.3/bin/neo4j start
  - mysql -e 'create database database_cleaner_test;'
  - psql -c 'create database database_cleaner_test;' -U postgres
  - docker exec sqlserver sh -c '/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "$SA_PASSWORD" -Q "create database database_cleaner_test"'
  - cp db/sample.config.yml db/config.yml
services:
  - redis-server
  - mongodb
  - docker
cache:
  bundler: true
  directories:
    - neo4j-community-2.3.3

